### ISSUE TITLE
Package for darwin_arm64

### ISSUE THREAD

**Issue by sagepe** [brightbox/terraform-provider-brightbox#14]
I've just switched to a new Apple Silicon Macbook Pro and see the following when running `terraform init`:

```
Provider registry.terraform.io/brightbox/brightbox v2.0.6 does not have a package available for your current platform, darwin_arm64.
```

Are there any plans to provide a compatible package?

**Comment by NeilW** [comment]
Well that's a bit of an oversight isn't it!

I've bumped the go version to 1.17 and released version 2.0.7 which should have the darwin_arm64 executable you require. 

Hopefully that will get you working again, but if there are any issues with it please let me know.
